name: Test Script Parsing

on:
  workflow_dispatch:
    branches:
      - 'workflow-test-*'
      - 'main'
    inputs:
      tag_name:
        description: 'Tag à tester'
        required: true
        default: 'back-v1.2.3'


jobs:
  test-parsing:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Afficher toutes les variables
        shell: bash
        run: |
          echo "=== Variables GitHub ==="
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          
          echo "=== Test du parsing ==="
          REF_NAME="${GITHUB_REF_NAME}"
          echo "REF_NAME: $REF_NAME"
          echo "Component (extraction): ${REF_NAME%%-*}"
          echo "Version (extraction): ${REF_NAME#*-v}"
          
          echo "=== test Pattern ==="
          if [[ "$REF_NAME" == back-v* ]]; then 
            echo "✅ Match back-v*"
          else 
            echo "❌ No match back-v*"
          fi
          
          if [[ "$REF_NAME" == front-v* ]]; then 
            echo "✅ Match front-v*"
          else 
            echo "❌ No match front-v*"
          fi

      - name: Test avec tag personnalisé
        shell: bash
        run: |
          echo "=== Input reçu: ${{ github.event.inputs.tag_name }} ==="
          echo "=== Test avec tag input ==="
          
          REF_NAME="${{ github.event.inputs.tag_name }}"
          echo "REF_NAME testé: $REF_NAME"

          if [[ "$REF_NAME" == back-v* ]]; then echo "component=back" >> $GITHUB_OUTPUT; fi
          if [[ "$REF_NAME" == front-v* ]]; then echo "component=front" >> $GITHUB_OUTPUT; fi
          VERSION="${REF_NAME#*-v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
          echo "=== Résultats ==="
          cat $GITHUB_OUTPUT
