name: Release Please Backend

on:
  workflow_run:
    workflows: ["Backend CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-backend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if commit is from release merge
        id: check_release
        run: |
          # Vérifier si le dernier commit provient d'un merge de release
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")

          if [[ "$COMMIT_MESSAGE" =~ ^chore\(main\):\ release || "$COMMIT_AUTHOR" == "github-actions[bot]" ]]; then
            echo "skip_release=true" >> $GITHUB_OUTPUT
            echo "Commit détecté comme un merge de release, skip du workflow"
          else
            echo "skip_release=false" >> $GITHUB_OUTPUT
            echo "Commit normal, poursuite du workflow"
          fi
      - uses: googleapis/release-please-action@v4
        if: steps.check_release.outputs.skip_release != 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config-backend.json
          manifest-file: .github/.release-please-manifest-backend.json
