name: Release Please Simple

on:
  push:
    branches:
      - main
      - workflow-test-*
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  release-please-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: java
          package-name: bobapp-back
          path: back
          changelog-path: back/CHANGELOG.md

  release-please-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: bobapp-frontend
          path: front
          changelog-path: front/CHANGELOG.md
