name: Release Please Frontend

on:
  workflow_run:
    workflows: ["Frontend CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please-frontend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4.0.0
        id: release_please
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config-frontend.json
          manifest-file: .github/.release-please-manifest-frontend.json

      - name: Login to Docker Hub
        if: ${{ steps.release_please.outputs.release_created == 'true' || steps.release_please.outputs.releases_created == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Déterminer la version d'image
        id: info
        if: ${{ steps.release_please.outputs.release_created == 'true' || steps.release_please.outputs.releases_created == 'true' }}
        shell: bash
        run: |
          TAG="${{ steps.release_please.outputs.tag_name }}"
          if [[ -z "$TAG" ]]; then
            echo "tag_name vide (aucune release créée ou sortie indisponible)."
            exit 1
          fi

          # Extrait la version: support "bobapp-frontend-vX.Y.Z" ou "vX.Y.Z"
          if [[ "$TAG" == *"-v"* ]]; then
            VERSION="${TAG##*-v}"
          else
            VERSION="${TAG#v}"
          fi

          echo "component=front" >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Tag détecté: ${TAG} -> version=${VERSION}"

      - name: Build and push Docker image (latest + version)
        if: ${{ steps.release_please.outputs.release_created == 'true' || steps.release_please.outputs.releases_created == 'true' }}
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./front
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-${{ steps.info.outputs.component }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-${{ steps.info.outputs.component }}:${{ steps.info.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.info.outputs.version }}
