name: Analyse SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration JDK 17 #SonarCloud a besoin de java17 !
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Exécution des tests backend et génération des rapports
      - name: Build et test backend
        run: |
          cd back
          mvn -B verify org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report

      # Configuration Node.js pour le frontend
      - name: Configuration Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'

      # Exécution des tests frontend et génération des rapports
      - name: Build et test frontend
        run: |
          cd front
          npm ci
          npm test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      # Analyse SonarCloud
      - name: Analyse SonarCloud
        uses: SonarSource/sonarqube-scan-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
