name: Analyse SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarcloud-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Cache des packages SonarCloud
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Construction et analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bobapp-backend -Dsonar.organization=cpierres -Dsonar.host.url=https://sonarcloud.io

  sonarcloud-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'

      - name: Installation des dépendances
        run: npm ci

      - name: Exécution des tests avec couverture
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=bobapp-frontend
            -Dsonar.organization=cpierres
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
