# Nom du workflow qui apparaîtra dans l'interface GitHub
name: Run Tests

# Définit quand le workflow sera déclenché
on:
  # Se déclenche lors d'un push sur la branche master
  push:
    branches: [ master ]
  # Se déclenche lors d'une pull request vers la branche master
  pull_request:
    branches: [ master ]

# Liste des jobs à exécuter
jobs:
  # Définition du job "backend-tests"
  backend-tests:
    # Utilise la dernière version d'Ubuntu comme environnement d'exécution
    runs-on: ubuntu-latest
    # Configure le répertoire de travail par défaut pour toutes les commandes
    defaults:
      run:
        working-directory: ./back

    # Liste des étapes à exécuter dans ce job
    steps:
      # Récupère le code source du dépôt
      - uses: actions/checkout@v3

      # Configure Java 11 pour l'environnement
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'    # Utilise AdoptOpenJDK
          cache: maven            # Active le cache Maven

      # Exécute les tests avec Maven
      - name: Run tests with Maven
        run: mvn test

      # Génère le rapport de couverture JaCoCo
      - name: Generate JaCoCo Report
        run: mvn jacoco:report

      # Téléverse le rapport JaCoCo comme artefact
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report    # Nom de l'artefact
          path: back/target/site/jacoco/  # Chemin vers les rapports

      # Publie les résultats des tests JUnit
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()    # S'exécute même si les étapes précédentes échouent
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'  # Chemin des rapports
          fail_on_failure: true  # Échoue si les tests échouent